title:       Security and Safety in Machine Learning Systems 
description: Workshop at ICLR 2021

# timezone: Europe/Zurich

navigation:
  Home: "/aml-iclr2021"
  Call for Papers: "/aml-iclr2021/cfp"
  Schedule: "/aml-iclr2021/schedule"
  Speakers: "/aml-iclr2021/speakers"
  # Accepted Papers: "/papers"
  Organizers: "/aml-iclr2021/organizers"
  Program Committee: "/aml-iclr2021/committee"
  Previous Workshops: "/aml-iclr2021/previous"
  # FAQ: "/faq"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
